### ISSUE TITLE
Architecture compatibility

### ISSUE THREAD

**Issue by JM-Lemmi** [cirosec-studis/zimbraweb-smtp-bridge#1]
This container should ideally run on x86 and arm

**Comment by frereit** [comment]
Currently GH Actions only builds x86_64 images.

Building on RaspberryPi works after upgrading libseccomp2 (good thing we use Python and not a compiled language or we'd have to recompile for every platform!):

https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/

```
# Get signing keys to verify the new packages, otherwise they will not install
rpi ~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138

# Add the Buster backport repository to apt sources.list
rpi ~$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list

rpi ~$ sudo apt update
rpi ~$ sudo apt install libseccomp2 -t buster-backports
```
Adding ARM images with GitHub Actions should be doable pretty easily: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
