### ISSUE TITLE
Fallback SMTP

### ISSUE THREAD

**Issue by JM-Lemmi** [cirosec-studis/zimbraweb-smtp-bridge#16]
Configurable options for Fallback

1. zimbraweb transport
2. SMTP with relay
3. Direct SMTP

Option 2 would need to be configured with an SMTP Server that will pass Mails for any Domain.

Option 3 should be disabled by default, but can be enabled by the User. It will also most likely fail, since residential IPs are blocked by most E-Mail providers.

**Comment by frereit** [comment]
How do we do Option 2? As far as I can tell, Postfix only has a [smtp_fallback_relay](http://www.postfix.org/postconf.5.html#smtp_fallback_relay) configuration parameter, which is used for emails that have no other transport associated with them. Because our transport is associated for `*`, the fallback relay would never be used I think.

Do we "manually" use the fallback relay in the python script? or is there a way to configure postfix to do what we want?

**Comment by JM-Lemmi** [comment]
[r/postfix Post for Help](https://www.reddit.com/r/postfix/comments/r5o3qh/how_to_configure_a_fallback_for_transport_rules/?utm_source=share&utm_medium=web2x&context=3)

**Comment by JM-Lemmi** [comment]
Removing the milter and adding `postconf -e smtp_fallback_relay=172.17.0.3` does not work, as expected.

If the Reddit Post does not turn up additional settings, I think the best way would be to handle it in the python script.

**Comment by JM-Lemmi** [comment]
Differentiating could be done depending on `pickup` oder `smtpd`

### local

```
2021-12-01T15:36:48.308663+00:00 INFO    postfix/pickup[187]: 4B4C8185D1: uid=0 from=<s212689@student.dhbw-mannheim.de>
2021-12-01T15:36:48.314186+00:00 INFO    postfix/cleanup[1454]: 4B4C8185D1: message-id=<abcd0123@student.dhbw-mannheim.de>
2021-12-01T15:36:48.318637+00:00 INFO    postfix/qmgr[188]: 4B4C8185D1: from=<s212689@student.dhbw-mannheim.de>, size=1252, nrcpt=1 (queue active)
2021-12-01T15:36:49.674282+00:00 INFO    postfix/smtp[1456]: 4B4C8185D1: to=<s212689@student.dhbw-mannheim.de>, relay=bama6.ba-mannheim.de[141.72.3.10]:25, delay=1.4, delays=0.03/0.01/0.9/0.44, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 1C9F211FE7F)
2021-12-01T15:36:49.679468+00:00 INFO    postfix/qmgr[188]: 4B4C8185D1: removed
```

### remote

```
2021-12-01T15:43:56.007434+00:00 INFO    postfix/smtpd[1188]: connect from unknown[172.17.0.3]
2021-12-01T15:43:56.023277+00:00 INFO    postfix/smtpd[1188]: 05A3918A58: client=unknown[172.17.0.3]
2021-12-01T15:43:56.028585+00:00 INFO    postfix/cleanup[1600]: 05A3918A58: message-id=<>
2021-12-01T15:43:56.041657+00:00 INFO    postfix/qmgr[188]: 05A3918A58: from=<s212689@student.dhbw-mannheim.de>, size=484, nrcpt=1 (queue active)
2021-12-01T15:43:56.041996+00:00 INFO    postfix/smtpd[1188]: disconnect from unknown[172.17.0.3] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
2021-12-01T15:43:57.513491+00:00 INFO    postfix/smtp[1577]: 05A3918A58: to=<s212689@student.dhbw-mannheim.de>, relay=bama6.ba-mannheim.de[141.72.3.10]:25, delay=1.5, delays=0.03/0/0.52/0.95, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 6F97411FE8D)
2021-12-01T15:43:57.513873+00:00 INFO    postfix/qmgr[188]: 05A3918A58: removed
```

**Comment by JM-Lemmi** [comment]
This article seems to be helpful for this topic: https://www.linuxbabe.com/mail-server/postfix-transport-map-relay-map-flexible-email-delivery

**Comment by JM-Lemmi** [comment]
❓ is the user the script is running as allowed to use the -f with Sendmail

**Comment by JM-Lemmi** [comment]
> Note, you should not attempt to deliver large volumes of mail via the [pickup(8)](http://www.postfix.org/pickup.8.html) service. High volume sites should avoid using "simple" content filters that re-inject scanned mail via Postfix [sendmail(1)](http://www.postfix.org/sendmail.1.html) and [postdrop(1)](http://www.postfix.org/postdrop.1.html).

> The "postsuper -r" command can place selected messages into the ["maildrop" queue](http://www.postfix.org/QSHAPE_README.html#maildrop_queue) for reprocessing.

http://www.postfix.org/QSHAPE_README.html#maildrop_queue

**Comment by JM-Lemmi** [comment]
Running multiple Postfix instances instead of crossing them over might be the better solution:

> A single Postfix configuration can provide many or all of these services, but a complex interplay of settings may be required, [...]. In this document we take the view that multiple Postfix instances may be a simpler way to configure a multi-function Postfix system. With multiple Postfix instances, each instance has its own directories for configuration, queue and data files, but it shares all Postfix program and documentation files with other instances.

http://www.postfix.org/MULTI_INSTANCE_README.html

**Comment by JM-Lemmi** [comment]
To my understanding multi instancing would be the "right" solution in this case. But I fear that this significantly bloats the image for a function not everyone might use.

Maybe there is a simpler and lighter alternative. Maybe a simple SMTP client that doesn't rely on the local MTA, basically the equivalent to powershells `Send-MailMessage`. Or even easier, a python SMTP client that can deal with the full eml?

Whats your opinion @frereit ?

**Comment by JM-Lemmi** [comment]
I've now started on the multi instancing, but maybe I should look into this:

> Use the "relay" transport for inbound mail, and the default "smtp" transport for outbound mail.

[`relay_domains`](http://www.postfix.org/postconf.5.html#relay_domains)

**Comment by JM-Lemmi** [comment]
### Delivery from the inside fails:

```log
Dec 03 17:26:37 248e71f51319 postfix-zimbra/pipe[221]: E9C9527978: to=<s212689@student.dhbw-mannheim.de>, relay=zimbrawebtransport, delay=0.24, delays=0.02/0/0/0.22, dsn=2.0.0, status=sent (delivered via zimbrawebtransport service (INFO:root:send_mail started! ERROR:root:Trying to send unauthenticated bounce-email to non-authentic))
```

### delivery from outside fails
```powershell
PS C:\Users\julian.lemmerich\Github\zimbraweb-smtp-bridge> Send-MailMessage -SmtpServer localhost -Port 587 -From s212689@student.dhbw-mannheim.de -To s212689@student.dhbw-mannheim.de -Credential (Get-Credential) -Subject "[Test] Testnachricht" -Body "Dies ist eine Testmessage aus Powershell f09"

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Send-MailMessage : Unable to read data from the transport connection: net_io_connectionclosed.
At line:1 char:1
+ Send-MailMessage -SmtpServer localhost -Port 587 -From s212689@studen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.Mail.SmtpClient:SmtpClient) [Send-MailMessage], SmtpException
    + FullyQualifiedErrorId : SmtpException,Microsoft.PowerShell.Commands.SendMailMessage
```

even telnet cant connect

### postfix already running

There is also a weird error in the zimbra log. But the zimbra instance seems to be running anyway.

```
Dec 03 17:24:33 248e71f51319 postfix-zimbra/postfix-script[96]: starting the Postfix mail system
Dec 03 17:24:33 248e71f51319 postfix-zimbra/master[98]: daemon started -- version 3.6.2, configuration /etc/postfix-zimbra
Dec 03 17:24:34 248e71f51319 postfix-zimbra/postfix-script[189]: fatal: the Postfix mail system is already running
```

**Comment by JM-Lemmi** [comment]
### Re: Delivery from the inside fails

My mistake, I should have known obviously. Without the SASL auth, send_mail is unable to authenticate to zimbra, thus the mail fails.

**Comment by JM-Lemmi** [comment]
> ### devlivery from outside fails

It seems, that postfix is not listening on that port, though I don't know why it wouldnt.

```
/ # nc -p 587
nc: bind: Address in use
/ # netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      104/dovecot
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      104/dovecot
tcp        0      0 127.0.0.1:587           0.0.0.0:*               LISTEN      -
tcp        0      0 :::143                  :::*                    LISTEN      104/dovecot
tcp        0      0 :::993                  :::*                    LISTEN      104/dovecot
```

Something is listening, but netstat doesn't show what process it is. Its also only on the loopback interface.

**Comment by JM-Lemmi** [comment]
Also solved that issue. It was a simple configuration error. The "inet" type was set to loopback only.

**Comment by JM-Lemmi** [comment]
@frereit This problem I think you can help, since you made the SASL auth:

```
Dec 03 19:03:26 d290aadff131 postfix/submission/smtpd[195]: warning: SASL: Connect to private/auth failed: No such file or directory
Dec 03 19:03:26 d290aadff131 postfix/submission/smtpd[195]: fatal: no SASL authentication mechanisms
```

The path is also in main.cf:

```
smtpd_sasl_path=private/auth
```

and in master.cf
```
submission inet n - n - - smtpd
 -o syslog_name=postfix/submission
 -o smtpd_sasl_auth_enable=yes
 -o smtpd_sasl_path=private/auth
 -o smtpd_client_restrictions=permit_sasl_authenticated,reject
```

I am not sure, what this is referring to and why this doesn't work on this instance, but on the regular container.

**Comment by JM-Lemmi** [comment]
Fixed it. The spool path in dovecot was wrong.

**Comment by JM-Lemmi** [comment]
The python `os.system` seems to fail when called by postfix.

```
Dec 04 15:23:53 1ca23bb26dce postfix-zimbra/pipe[217]: 905FF28396: to=<s212689@student.dhbw-mannheim.de>, relay=zimbrawebtransport, delay=0.32, delays=0.01/0/0/0.3, dsn=2.0.0, status=sent (delivered via zimbrawebtransport service (INFO:root:send_mail started! INFO:root:Mail is unparsable. Using Relay. sh: sendmail: not found))
```

When calling the function in python directly it works as expected. I feel like we have run into a similar issue before.

```
/ # su posttransport
/ $ cat /tmp/mailtransport.eml | sendmail -f "s212689@student.dhbw-mannheim.de" s212689@student.dhbw-mannheim.de
/ $ python
Python 3.9.5 (default, May 12 2021, 20:44:22) 
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.system('cat /tmp/mailtransport.eml | sendmail -f "s212689@student.dhbw-mannheim.de" s212689@student.dhbw-mannheim.de')
0
```

I already tried:
* changed from formatstrings to literal strings
* removed `"`
* changed from `echo` to `cat`

**Comment by JM-Lemmi** [comment]
```
sendmail: fatal: User posttransport(1000) is not allowed to submit mail
```

I dont get why? Especially because the script again works directly from the python interactive shell.

According to the [docs](http://www.postfix.org/postconf.5.html#authorized_submit_users)

> By default, all users are allowed to submit mail.

Maybe its still running as postfix some way and that is not allowed?

> Otherwise, the real UID of the process is looked up in the system password file

**Comment by JM-Lemmi** [comment]
> Maybe a simple SMTP client that doesn't rely on the local MTA,

I should have known there is a better python library.

[python smtplib](https://docs.python.org/3/library/email.examples.html#:~:text=own%20SMTP%20server.-,with%20smtplib.SMTP(%27localhost%27)%20as%20s%3A%0A%20%20%20%20s.send_message(msg),-Here%E2%80%99s%20an%20example)

```python
>>> type(msg)
email.MailMessage
>>> with smtplib.SMTP('relayhost') as s:
...    s.send_message(msg)
```

So all of the work with postfix multi instancing was for naught, but at least I found a way easier version than trying to maintain multiple versions of the container.
