### ISSUE TITLE
Clean up auth tokens on `close` with milter

### ISSUE THREAD

**Issue by frereit** [cirosec-studis/zimbraweb-smtp-bridge#31]
The auth tokens in shared memory (`/dev/shm/auth_XXXX`) can be deleted once `close` is called in the milter.

**Comment by frereit** [comment]
This idea doesn't work. The SMTP connection is closed before the mail is actually delivered with send_mail.py, so deleting the auth token with the milter doesn't work.

We *could* delete the auth token after every call to `send_mail.py`. I don't know of any mail client that sends multiple mails with a single auth session but it's technically possible with SMTP. Removing the auth token would make that impossible. 

I don't really know what to do here. We could "schedule" the auth tokens to be deleted 5 minutes after they've been created (via crontab)? I don't think a single SMTP session should last 5 minutes. Stills feels a bit hacky though, please advise @JM-Lemmi

**Comment by JM-Lemmi** [comment]
I would assume that having multiple mails in your outgoing folder will lead to sending multiple mails with the same auth session. You can even see this behaviour in Powershells `Send-MailMessage` where sending multiple Test mails in succession (each with their own command) will utilize the same connection. So it should not delete the auth token after one E-Mail.

Deleting them via cron might be unlucky and the job is executed right in between auth and sending the mail.

I think the cleanest way to do this would be to spawn another process that executes `sleep 600; rm /dev/shm/auth_XXXX`

**Comment by frereit** [comment]
> Deleting them via cron might be unlucky and the job is executed right in between auth and sending the mail.

Sorry, I was unclear. I mean running a cron tab every 5 minutes to delete all auth tokens that were created more than 5 (10? 15?) minutes ago

**Comment by JM-Lemmi** [comment]
That sounds reasonable and a bit simpler than my idea

**Comment by frereit** [comment]
Whoops 😅 I commited straight to develop. Sorry. Since this is such a small commit, I think it's fine to just leave it like this, though feel free to check out the commit @JM-Lemmi  and lmk if you want anything changed.
