### ISSUE TITLE
Sending email to the host of the Docker Container fails.

### ISSUE THREAD

**Issue by frereit** [cirosec-studis/zimbraweb-smtp-bridge#34]
## Reproducing

Start the docker container with the hostname "dhbw-mannheim.email." 

Try to send an email to "hello@dhbw-mannheim.email". The email is rejected with a "temporary lookup failure"
![image](https://user-images.githubusercontent.com/18506129/141944999-33892761-2ec7-4064-9975-1ea11057ece1.png)

I assume this is because Postfix thinks the email is meant for a local user. I don't really think there is a simple way to fix it and I don't really think it's worth the effort. Maybe we should just add a disclaimer that the hostname of the docker container must **not** be "student.dhbw-mannheim.de" and then call it wontfix?

**Comment by JM-Lemmi** [comment]
You can disable local transport: http://www.postfix.org/postconf.5.html#local_transport
