### ISSUE TITLE
Clean up container stdout

### ISSUE THREAD

**Issue by JM-Lemmi** [cirosec-studis/zimbraweb-smtp-bridge#41]
- [x] There is no need to print the full MIME-Mail to stdout from the milter
- [x] postfix does not log message actions?
- [x] print logs from all python components
- [x] unify log format from python (this includes date and issuing program)
- [x] Stop Milter from taking over stdout; zimbra_milter log to file
- [x] unify log format of tls generation

**Comment by JM-Lemmi** [comment]
Waiting on #43

**Comment by JM-Lemmi** [comment]
@frereit For some reason, all stdout stops as soon as the milter is started. From then on only the milter can print to stdout (both with `logging.info()` and with `print()`). I don't quite see why that would be the case. Maybe you can have a look?

Milter.py even logs to stdout if if the logging.FileHandler is set to a file instead of stdout???

**Comment by JM-Lemmi** [comment]
I think it has to do with the order in which start.sh executes the programs.

Starting zimbra_milter.py in the background and adding tail as the last command into start.sh will keep the container running and display the maillog.

**Comment by frereit** [comment]
Yup, the logging is a bit messy, I will take a look tomorrow.

**Comment by JM-Lemmi** [comment]
Maybe this is the "correct" solution, but is it overkill? I'd like for the log format to be the same as for postfix, that makes reading it much nicer.

Maybe this is the "correct" solution, but is it overkill? https://stackoverflow.com/a/55584223

**Comment by JM-Lemmi** [comment]
```python
import sys, logging, platform

class HostnameFilter(logging.Filter):
    hostname = platform.node()

    def filter(self, record):
        record.hostname = HostnameFilter.hostname
        return True

handler = logging.StreamHandler(sys.stdout)
handler.addFilter(HostnameFilter())
handler.setFormatter(logging.Formatter('%(asctime)s %(hostname)s python/authentication.py: %(message)s', datefmt='%b %d %H:%M:%S'))

handlers = [handler]
logging.basicConfig(handlers=handlers, level=logging.INFO)

logging.info("Test")
```

This will produce the log format, that I want.
